fix(log): support nginx built without variadic macros
Fixed the error below, caused by a different signature of
`ngx_log_error_core` when neither `NGX_HAVE_C99_VARIADIC_MACROS` nor
nor `NGX_HAVE_GCC_VARIADIC_MACROS` is detected.
An example of affected configuration is MinGW with clang or gcc, where
we skip most of the compiler feature checks.

```
error[E0061]: this function takes 5 arguments but 6 arguments were
supplied
     --> examples\awssig.rs:312:9
      |
312   |         ngx_log_debug_http!(request,  "headers {:?}",  headers);
      |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unexpected argument #6 of type `*const u8`
      |
note: expected `*mut i8`,  found `usize`
```